version: '3'

services:
  nginx:
    image: nginx:1.17.8
    ports:
      - 8000:8080
    volumes:
      - ./docker-compose/nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./:/app
    links:
      - php

  php:
    build: ./docker-compose/php
    container_name: 'emissor-nota-fiscal-php'
    volumes:
      - ./:/app
