version: '3'

services:
  nginx:
    image: nginx:1.17.8
    ports:
      - 8000:8080
    volumes:
      - ./docker-compose/nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./:/app
    links:
      - php

  php:
    build: ./docker-compose/php
    container_name: 'emissor-nota-fiscal-php'
    volumes:
      - ./:/app
    links:
      - "mysql"

  mysql:
    image: mysql:latest
    container_name: 'emissor-nota-fiscal-mysql'
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'barbearia'
      MYSQL_PASSWORD: 'barbearia@123'

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 81:80
    environment:
      - PMA_ARBITRARY=1
    links:
      - "mysql"
